### PR TITLE
Update 06_react_and_flux.md

### PR DESCRIPTION
**Pull request by af7**
I am not sure if I get it right (most likely not), but shouldn't this be "coupled"?

### CODE REVIEW

**Comment by bebraw** [comment]
Good catch! Thanks for the fix.

Btw I went through the material at a session today and noticed a bunch of smaller issues to fix.

**Comment by af7** [comment]
You are doing a great work, by the way. As I am new here, should I "Delete Branch" now or this is not necessary?

**Comment by af7** [comment]
I know this is completely irrelevant: I am using your code (from this example 06) for trying to learn and I added the "React Dev Tools for Chrome" to debug, etc.

However, the "Top Level" *continuously* refreshes inside React Tools. So I cannot do anything debug-wise! It appears as if it is created and re-created continuously. Do you have any idea what the case may be? Thanks!

**Comment by bebraw** [comment]
> You are doing a great work, by the way. As I am new here, should I "Delete Branch" now or this is not necessary?

You can delete the branch if you want. It won't make much difference from my perspective.

In case you have other fixes in mind, you can [sync your master](https://help.github.com/articles/syncing-a-fork/) and then create a branch per patch:

```
git branch feature-name
git checkout feature-name
... do changes
git push
... create PR at GitHub
```

It might be faster to open issues here as you notice things. I'll be able to fix them quite fast that way.

--

I opened a separate issue (#10) for your React Dev Tools problem. I have a rough idea what might be causing it but we'll see.

**Pull request merged**
