### PR TITLE
07 from singletons to instances fixes

### PR DESCRIPTION
**Pull request by firedev**
What lodash is for here? It works without it.

### CODE REVIEW

**Comment by bebraw** [comment]
Good point about lodash. It is introduced later in the text at

```javascript
var d = _.isArray(_.get(data, 'notes')) ? data : {notes: []};

...
```

That said maybe it would be a good idea to rewrite lodash out? Then it would be something like

```javascript
var d = Array.isArray(data && data.notes? data : {notes: []};

...
```

Would that look good to you?

**Comment by firedev** [comment]
Yep. I mean we're using ES7 left and right, why add this dependency?

**Comment by firedev** [comment]
Polyfill? Why? http://kangax.github.io/compat-table/es5/#Array.isArray

**Comment by bebraw** [comment]
> Polyfill? Why? http://kangax.github.io/compat-table/es5/#Array.isArray

Ah, that's looking good! No need to support old-IE so we can go with the proposed. I'll update the code. :+1:

**Pull request merged**
