### PR TITLE
Fix undefined for this

### PR DESCRIPTION
**Pull request by guyellis**

### CODE REVIEW

**Comment by bebraw** [comment]
Thanks!

What would you think of applying [@autobind](https://github.com/andreypopp/autobind-decorator) for methods across the book? That would eliminate a lot of bindings (`() => ...`) that I find annoying. At least adopting that would make the code a little cleaner in my eyes.

**Comment by guyellis** [comment]
@autobind is a great idea. Just have a little explanation snippet when you introduce it showing what the alternative is.

**Comment by bebraw** [comment]
@guyellis I gave `@autobind` a go. Unfortunately it didn't work out as well as I had hoped. I'll leave this open, though, as it would be great to resolve this.

**Comment by bebraw** [comment]
Just realized this was a PR... I set up an issue that can be tracked. See #84.

**Pull request merged**
