### PR TITLE
More intention-revealing name

### PR DESCRIPTION
**Pull request by firedev**

### CODE REVIEW

**Comment by bebraw** [comment]
Thanks!

**Comment by firedev** [comment]
Sorry, wait, maybe it's not state, but notes array should be passed here and I got it all wrong and now ended up storing the object.

**Comment by bebraw** [comment]
No worries. I'll patch it.

**Comment by bebraw** [comment]
Actually the naming you proposed is perfect. `storeChanged` will receive something like `{notes: Array[2]}` in this case so that's fine. `setState` expects an object so looks good to me.

@firedev Is it failing for you in some particular way? I started from chapter 5 code and worked till `On Component Design`. Seemed as expected to me (ie. I saw a list of notes to modify). If there's some inconsistency within chapter 5 and you are not seeing the same, there's something missing in that chapter.

**Comment by firedev** [comment]
Well I am rebuilding the app moving along with the book and it all went fine until I got to decorators. It seems that passing `{notes: array}` and just `[task: '', task:'']` somehow got mixed up and that causes some incosistencies now. I have changed my code accordingly but then it struck me that maybe it's not what you have intended. Think I need to put it down for a bit. 

I would like to hear your comments about store initialization in decorators in this chapter. I see you're mentioning `NoteAction.init` passed down to decorator but it is never appearing in the actual code. Plus you mention it as it was passed as the first parameter which is incorrect as well.

**Comment by bebraw** [comment]
@firedev I walked through the chapter and fixed a bunch of gotchas. Thanks for pointing me to this direction. Can you give it another go? Sorry for the trouble!

**Pull request merged**
