### PR TITLE
01_webpack_compared.md copyedits

### PR DESCRIPTION
**Pull request by snowyplover**
While I've only read the first couple of chapters at this point, I'm finding the book quite helpful and informative. Thank you for making it available.

I have gone through this chapter and suggested some edits. I mostly did one commit per line, so there are a lot of commits. However, the suggestions are largely minimal. Most are small grammatical fixes and added commas. The rest address improper idioms or sentence flow issues.

The second commit labeled as line 146 actually refers to line 158. Unfortunately, the label seems to be impossible to fix from github, and I don't know git well enough to do it manually yet.

### CODE REVIEW

**Comment by bebraw** [comment]
@snowyplover Great! I'll get to these tomorrow. Busy day at a conference.

Would it be possible for you to rebase against `dev`? I maintain the development version there. I think I'll turn `master` into the dev version soon and do `stable` branch to make it easier to contribute in the near future.

**Comment by bebraw** [comment]
About rebasing, if it feels too difficult, don't worry. I can deal with it some other way. :+1:

**Comment by bebraw** [comment]
@snowyplover I figured out a neat solution for this. Now the repo defaults to `dev` so PRs will be done against it by default. Simple as that. I'll look into merging your work next while trying to learn from it. :+1:

**Comment by bebraw** [comment]
Merged manually! Thanks a lot.

**Comment by snowyplover** [comment]
@bebraw -
You're welcome! Glad this was useful.

Sorry about the extra bother with the branches, though it appears to have worked out ok.

**Comment by bebraw** [comment]
No worries. I simplified the setup as a result so it's easier to contribute
now. So it was a win overall. :)

Thanks again.

**Pull request closed without merging**
