### PR TITLE
Remove unnecessary comma

### PR DESCRIPTION
**Pull request by ericdouglas**

### CODE REVIEW

**Comment by bebraw** [comment]
What do you think of trailing commas in general?

Personally I like to use them as it keeps diffs neater. Back in the day they causes issues with IE but that's not a problem anymore as the source will either run over Node.js or go through Babel.

I could do a general pass to make sure this is consistent and add a remark about it.

**Comment by ericdouglas** [comment]
I just think that's unnecessary because is the last property of the object, and I thought that it was a typo.

:smile:

**Comment by bebraw** [comment]
Ok. I suppose I'll do a trailing comma pass and make sure it's consistent everywhere. Thanks for bringing this to my attention.

**Comment by ericdouglas** [comment]
You're welcome! And thanks for this great material!

**Pull request closed without merging**
